/**
 * Trae Code (traecli) Bento Adapter。
 *
 * capability spike 结论(.spike-trae/,traecli 0.202.1-tob 官方 ToB 发行,macOS arm64):
 *   - `traecli acp serve` 走 ACP;默认 legacy 后端在 session/new 硬性要求 TRAE
 *     企业账号登录(authMethods 只有 trae-tob-browser / trae-tob-pat);
 *     `TRAE_ACP_BACKEND=app-server` 后端可完全无登录使用(0.202.1 实测);
 *   - 配置隔离:`TRAE_HOME` 是 traecli.toml 与会话 rollout 的根,`TRAECLI_HOME`
 *     是 sqlite/日志/沙箱自复制等状态目录;两者都指到会话隔离目录即可完整隔离,
 *     不继承宿主 ~/.trae 登录态;
 *   - 自定义模型:`[[models]]` 数组项带 `[models.open_ai]`(base_url + "/chat/completions",
 *     SSE)或 `[models.claude]`(base_url + "/messages")后端 section;不登录也会
 *     出现在 `traecli models` 与 ACP model configOption 里;section 内 wire_api
 *     字段被静默忽略(open_ai 恒为 chat completions,不支持 responses wire);
 *   - api_key 以 Bearer 字面量发送(open_ai section 实测),因此配置只写占位凭证,
 *     真实鉴权由 loopback proxy 注入;
 *   - 跨 Provider live 切换:setSessionConfigOption(model, <[[models]].name>) 成功后
 *     下一请求命中切换后 Provider 的 mock 上游,PID 不变(spike 双 mock 实证);
 *   - resume:sessionCapabilities.resume/loadSession=true,新进程 resumeSession
 *     同一 sessionId 恢复,模型选择随 TRAE_HOME 内状态持久化;
 *   - 会话流只发 agent_message_chunk(+available_commands_update),不观测到
 *     tool_call update 与 requestPermission(工具在其 seatbelt 沙箱内自执行);
 *   - 无 reasoning effort 的 ACP configOption。
 *
 * 由此本 Adapter:
 *   prepare  = 全 Provider 完整 [[models]] 注册表(每 Provider 独立 loopback route,
 *              openai-chat → open_ai section、anthropic-messages → claude section,
 *              openai-responses 不受支持直接拒绝)+ TRAE_HOME/TRAECLI_HOME 隔离与
 *              TRAE_ACP_BACKEND=app-server;
 *   reconfigure = 注册表内任意选择 live(model configOption 实证);
 *   dispose = 吊销 routes,目录保留供 revive;彻底删除走 removeSessionState。
 */

import fs from "node:fs"
import path from "node:path"

import type { HarnessId } from "../../src/core/harness"
import type { WireProtocol } from "../../src/core/provider"
import type { ProviderRoutingService } from "../providers/provider-routing"
import { normalizeBentoModelId, stableProviderAlias } from "./alias"
import type {
  BentoModelSelection,
  PreparedModelRef,
  ReconfigureResult,
  SessionConfigAdapter,
  SessionConfigLease,
  SessionConfigRequest,
} from "./types"
import { selectionKey } from "./types"

/** 占位凭证:满足 traecli 的 Bearer/x-api-key 头要求,对任何真实上游无权限。 */
const PLACEHOLDER_CREDENTIAL = "bento-session-route"

/** traecli 自定义模型后端 section 与 Bento wire 协议的映射。 */
function traeModelSection(wireProtocol: WireProtocol): "open_ai" | "claude" | null {
  if (wireProtocol === "openai-chat") return "open_ai"
  if (wireProtocol === "anthropic-messages") return "claude"
  // openai-responses:traecli 的 [[models]] section 不支持 responses wire
  // (wire_api 字段被静默忽略,恒为 chat completions),代理也没有 chat→responses
  // 桥——如实拒绝,不静默降级。
  return null
}

/** TOML 基本字符串:JSON 转义与 TOML 兼容(引号/反斜杠/控制字符)。 */
function tomlString(value: string): string {
  return JSON.stringify(value)
}

export type TraeModelEntryInput = {
  providerId: string
  wireProtocol: WireProtocol
  modelId: string
}

/**
 * [[models]].name:ACP model configOption 的切换值。带 bento- 前缀避免与
 * traecli 内置目录(gpt-5.x 等)撞名;alias 跨会话稳定。
 */
export function traeModelName(providerId: string, modelId: string): string {
  return `${stableProviderAlias(providerId)}-${normalizeBentoModelId(modelId)}`
}

/** 生成完整 [[models]] 注册表(每项 base_url=该 Provider 的 loopback route)。 */
export function buildTraeSessionConfig(
  providers: Array<{
    providerId: string
    wireProtocol: WireProtocol
    models: Array<{ id: string }>
    baseUrl: string
  }>,
  defaultSlug: string,
): string {
  const lines: string[] = []
  for (const provider of providers) {
    const section = traeModelSection(provider.wireProtocol)
    if (!section) continue
    for (const model of provider.models) {
      const slug = normalizeBentoModelId(model.id)
      const name = traeModelName(provider.providerId, model.id)
      // open_ai 后端请求 {base_url}/chat/completions、claude 后端请求
      // {base_url}/messages;统一补 /v1 让代理侧与 Claude Code 的
      // base + /v1/messages 路径形状一致(代理再做 /v1 归一)。
      const baseUrl = `${provider.baseUrl.replace(/\/+$/, "")}/v1`
      lines.push(`[[models]]`)
      lines.push(`name = ${tomlString(name)}`)
      lines.push(``)
      lines.push(`[models.${section}]`)
      lines.push(`base_url = ${tomlString(baseUrl)}`)
      lines.push(`api_key = ${tomlString(PLACEHOLDER_CREDENTIAL)}`)
      lines.push(`model = ${tomlString(slug)}`)
      lines.push(``)
    }
  }
  lines.unshift(`# generated by Bento; credentials are injected by the loopback proxy`)
  lines.unshift(`model = ${tomlString(defaultSlug)}`)
  return `${lines.join("\n")}\n`
}

export class TraeBentoConfigAdapter implements SessionConfigAdapter {

  constructor(
    readonly harnessId: HarnessId,
    private readonly routing: ProviderRoutingService,
    private readonly userDataDir: string,
  ) {}

  async prepare(request: SessionConfigRequest): Promise<SessionConfigLease> {
    if (request.providers.length === 0) {
      throw new Error("没有可用的 Bento Provider,无法准备 Trae 会话配置")
    }
    for (const provider of request.providers) {
      if (!traeModelSection(provider.wireProtocol)) {
        throw new Error(
          `Provider ${provider.name} 的 ${provider.wireProtocol} 协议不受 Trae 支持(Trae 自定义模型仅支持 OpenAI Chat / Anthropic Messages)`,
        )
      }
    }

    const selections = new Map<string, PreparedModelRef>()
    const names = new Set<string>()
    for (const provider of request.providers) {
      for (const model of provider.models) {
        const name = traeModelName(provider.providerId, model.id)
        if (names.has(name)) {
          throw new Error(`Trae 模型名冲突: ${name}(Provider ${provider.providerId} 与其它条目归一后同名)`)
        }
        names.add(name)
        const ref: PreparedModelRef = {
          providerId: provider.providerId,
          modelId: normalizeBentoModelId(model.id),
          // ACP model configOption 的选项值就是 [[models]].name
          harnessModelId: name,
        }
        selections.set(selectionKey(ref.providerId, ref.modelId), ref)
      }
    }
    const selected = selections.get(selectionKey(
      request.selected.providerId,
      normalizeBentoModelId(request.selected.modelId),
    ))
    if (!selected) {
      throw new Error(
        `模型 ${request.selected.providerId}/${request.selected.modelId} 不在 Bento 注册表中`,
      )
    }

    // 每 Provider 独立 loopback route;auth/requestPath/fixedHeaders/OAuth 由 ProxyRoute 注入。
    const routeSet = await this.routing.issueRouteSet(
      request.sessionKey,
      request.providers.map((provider) => ({ providerId: provider.providerId, harnessId: request.harnessId })),
    )

    const configDir = path.join(this.userDataDir, "providers", `trae-bento-${request.sessionKey}`)
    try {
      fs.mkdirSync(configDir, { recursive: true, mode: 0o700 })
      fs.writeFileSync(path.join(configDir, "traecli.toml"), buildTraeSessionConfig(
        request.providers.map((provider) => ({
          providerId: provider.providerId,
          wireProtocol: provider.wireProtocol,
          models: provider.models,
          baseUrl: routeSet.get(provider.providerId)!.baseUrl,
        })),
        selected.modelId,
      ), { mode: 0o600 })
      // Skills 投递:复制进 TRAE_HOME/skills。已证实(traex 0.202.1-tob 二进制:
      // _trae_home() = os.environ.get("TRAE_HOME", "~/.trae"),skills 根 =
      // _trae_home()/"skills";其内置 skill 安装说明亦写 $TRAE_HOME/skills)。
      if (request.skills?.curatedRoot) {
        fs.cpSync(
          path.join(request.skills.curatedRoot, "skills"),
          path.join(configDir, "skills"),
          { recursive: true },
        )
      }
    } catch (error) {
      this.routing.revokeRoute(request.sessionKey)
      await this.removeSessionState(request.sessionKey)
      throw error
    }

    const sessionKey = request.sessionKey
    const routing = this.routing
    let disposed = false
    return {
      sessionKey,
      harnessId: request.harnessId,
      env: {
        TRAE_HOME: configDir,
        TRAECLI_HOME: configDir,
        // legacy 后端在 session/new 硬性要求 TRAE 企业登录;app-server 后端无此门槛(spike 实证)
        TRAE_ACP_BACKEND: "app-server",
      },
      strip: ["TRAE_HOME", "TRAECLI_HOME", "TRAE_ACP_BACKEND"],
      configDir,
      selections,
      selected,
      revision: 1,
      async dispose() {
        // 只释放活跃 routes;目录保留供离线 resume 复用同一 TRAE_HOME。
        if (disposed) return
        disposed = true
        routing.revokeRoute(sessionKey)
      },
    }
  }

  async reconfigure(lease: SessionConfigLease, next: BentoModelSelection): Promise<ReconfigureResult> {
    // 注册表内任意 Provider/模型 → model configOption live 切换(spike 实证,
    // 切换后请求命中新 Provider 的上游,进程不重启)。
    const ref = lease.selections.get(selectionKey(
      next.providerId,
      normalizeBentoModelId(next.modelId),
    ))
    if (ref) return { mode: "live", selection: ref }
    const reason = "该模型不在当前 Bento 注册表中,需要新会话"
    return { mode: "new-session", reason }
  }

  async removeSessionState(sessionKey: string): Promise<void> {
    const configDir = path.join(this.userDataDir, "providers", `trae-bento-${sessionKey}`)
    await fs.promises.rm(configDir, { recursive: true, force: true })
  }
}
